# generated by datamodel-codegen:
#   filename:  https://foundry-api-public.adaptyvbio.com/openapi.json
#   timestamp: 2026-01-06T16:21:59+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field, RootModel


class CreateExpResponse(BaseModel):
    experiment_id: str = Field(..., description="Unique identifier assigned to the new experiment")
    error: str | None = Field(None, description="Error message if creation failed")


class ExperimentConfirmationResponse(BaseModel):
    confirmed_at: str = Field(..., description="Timestamp when confirmation completed")
    experiment_id: str = Field(..., description="Experiment identifier")
    status: str = Field(
        ...,
        description='Experiment status after confirmation (e.g., "waiting_for_materials")',
    )
    stripe_invoice_id: str | None = Field(
        None, description="Stripe invoice identifier created during confirmation"
    )
    stripe_invoice_url: str | None = Field(
        None, description="Hosted invoice URL from Stripe (if available)"
    )


class ExperimentInvoiceResponse(BaseModel):
    experiment_id: str = Field(..., description="Experiment identifier")
    invoice_id: str | None = Field(None, description="Invoice ID when available")
    invoice_url: str | None = Field(None, description="Hosted invoice URL when available")
    status: str | None = Field(
        None, description="Invoice status (draft, open, paid, uncollectible, void)"
    )


class ExperimentQuoteResponse(BaseModel):
    amount_subtotal: int = Field(..., description="Subtotal amount (in the smallest currency unit)")
    amount_total: int = Field(..., description="Total amount (in the smallest currency unit)")
    currency: str = Field(..., description='ISO currency code (e.g., "usd")')
    experiment_id: str = Field(..., description="Experiment identifier")
    expires_at: str | None = Field(
        None,
        description="RFC3339 timestamp for when the quote expires (if provided by Stripe)",
    )
    quote_id: str = Field(..., description="Stripe quote identifier")
    status: str = Field(..., description="Stripe quote status")
    stripe_quote_url: str | None = Field(None, description="Stripe hosted quote URL")
    updated_at: str | None = Field(None, description="RFC3339 timestamp for the last update time")


class ExperimentStatus(str, Enum):
    draft = "draft"
    waiting_for_confirmation = "waiting_for_confirmation"
    canceled = "canceled"
    waiting_for_materials = "waiting_for_materials"
    in_production = "in_production"
    quote_sent = "quote_sent"
    in_queue = "in_queue"
    data_analysis = "data_analysis"
    in_review = "in_review"
    done = "done"
    error = "error"


class ExperimentType(str, Enum):
    affinity = "affinity"
    screening = "screening"
    thermostability = "thermostability"
    fluorescence = "fluorescence"
    expression = "expression"


class FrameworkRegions(BaseModel):
    ch: str | None = Field(None, description="Constant heavy chain region")
    cl: str | None = Field(None, description="Constant light chain region")


class Method(str, Enum):
    bli = "bli"
    spr = "spr"


class ResultsStatus(str, Enum):
    none = "none"
    partial = "partial"
    all = "all"


class SequenceType(str, Enum):
    sc_fv = "sc_fv"
    fab = "fab"
    single_chain = "single_chain"
    ig_g = "ig_g"


class TagLocation(str, Enum):
    n = "N"
    c = "C"


class TargetInfo(BaseModel):
    catalog_number: str = Field(..., description="Vendor's catalog/SKU number")
    id: str = Field(..., description="Unique identifier for the target from the catalog")
    name: str = Field(..., description="Product name of the target antigen")
    vendor_name: str = Field(..., description='Vendor/supplier name (e.g., "ACRO Biosystems")')


class TargetListItem(BaseModel):
    catalog_number: str = Field(..., description="Vendor's catalog/SKU number")
    id: str = Field(..., description="Unique identifier for the target from the catalog")
    name: str = Field(..., description="Product name of the target antigen")
    vendor_name: str = Field(..., description='Vendor/supplier name (e.g., "ACRO Biosystems")')


class UpdateListItem(BaseModel):
    experiment_code: str = Field(..., description="Experiment code for grouping and display")
    experiment_id: str = Field(..., description="ID of the experiment that generated this update")
    id: str = Field(..., description="Unique identifier for this update event (ULID)")
    name: str = Field(..., description="Public-facing name/title of the update")
    timestamp: str = Field(..., description="ISO 8601 timestamp when the update occurred")


class ExpListItem(BaseModel):
    code: str = Field(..., description='Unique experiment code (e.g., "EXP-2024-001")')
    created_at: str = Field(..., description="ISO 8601 timestamp of experiment creation")
    experiment_type: ExperimentType = Field(
        ..., description="Experiment discriminator from the spec"
    )
    experiment_url: str = Field(..., description="URL to view the experiment in the Foundry portal")
    id: str = Field(..., description="Unique identifier for the experiment")
    name: str = Field(..., description="Human-readable name for the experiment")
    results_status: ResultsStatus = Field(
        ..., description="Indicates whether results are available for this experiment"
    )
    status: ExperimentStatus = Field(..., description="Current lifecycle status of the experiment")
    stripe_invoice_id: str | None = Field(None, description="Stripe invoice ID if invoiced")
    stripe_quote_id: str | None = Field(None, description="Stripe quote ID if quote was generated")


class SequenceMetadata(BaseModel):
    chain_order: list[str] | None = Field(None, description="Chain ordering for complex formats")
    framework_regions: FrameworkRegions | None = None
    linker: str | None = Field(None, description="Linker sequence (for ScFv)")
    tag_location: TagLocation | None = None
    type: SequenceType | None = None
    vh: str | None = Field(None, description="Heavy chain variable region (for ScFv)")
    vl: str | None = Field(None, description="Light chain variable region (for ScFv)")


class TargetList(BaseModel):
    targets: list[TargetListItem] = Field(
        ..., description="Array of target summary items for the current page"
    )
    total: int = Field(..., description="Total number of targets available across all pages", ge=0)
    count: int = Field(..., description="Number of items returned in this response", ge=0)
    offset: int = Field(..., description="Offset from the start of the result set", ge=0)


class UpdateList(BaseModel):
    next_cursor: str | None = Field(
        None,
        description="Cursor for next page (use the last update's ID as cursor)\nNone if this is the last page",
    )
    updates: list[UpdateListItem] = Field(..., description="Array of recent update events")


class ExpList(BaseModel):
    experiments: list[ExpListItem] = Field(..., description="Array of experiment summaries")
    total: int = Field(..., description="Total number of experiments available across all pages", ge=0)
    count: int = Field(..., description="Number of items returned in this response", ge=0)
    offset: int = Field(..., description="Offset from the start of the result set", ge=0)


class SequenceInput(BaseModel):
    control: bool | None = Field(
        None, description="Whether the sequence should be treated as a positive control"
    )
    fasta: str = Field(
        ...,
        description="Protein/peptide sequence in standard single-letter amino acid format",
    )
    metadata: SequenceMetadata | None = None


class SequenceValue(RootModel[str | SequenceInput]):
    root: str | SequenceInput = Field(
        ...,
        description="Flexible sequence input for experiment creation.\n\nAccepts a simple FASTA string or a rich object with control flag and metadata.",
    )


class ExperimentSpec(BaseModel):
    antigen_concentrations: list[float] | None = Field(
        None, description="Antigen concentrations to test (in Molar)"
    )
    experiment_type: ExperimentType = Field(
        ..., description="Assay type: `affinity`, `screening`, or `thermostability`"
    )
    method: Method | None = Field(
        None, description="Measurement method (BLI or SPR). Defaults to BLI."
    )
    n_replicates: int | None = Field(
        None,
        description="Number of technical replicates (minimum 1, recommended 3+)",
        ge=0,
    )
    parameters: Any | None = Field(None, description="Additional experiment-specific parameters")
    sequences: dict[str, SequenceValue] | None = Field(
        None,
        description="Sequences keyed by a human readable name. Accepts either simple FASTA strings\nor rich objects with control flags and metadata.",
    )
    target_id: str | None = Field(None, description="UUID of the target antigen from the catalog")


class CreateExpRequest(BaseModel):
    experiment_spec: ExperimentSpec = Field(
        ...,
        description="Structured experiment definition (type, target, sequences, parameters)",
    )
    id: str | None = Field(
        None,
        description="Experiment UUID for updates. Omit to create a new experiment.",
    )
    name: str = Field(..., description="Human-readable name for the experiment")
    webhook_url: str | None = Field(
        None, description="URL to which experiment status updates will be POSTed"
    )


class ExpInfo(BaseModel):
    code: str = Field(
        ...,
        description='Unique experiment code (e.g., "EXP-2024-001") or request ID if not fulfilled',
    )
    created_at: str = Field(..., description="ISO 8601 timestamp of experiment creation")
    experiment_spec: ExperimentSpec = Field(
        ...,
        description="Unified experiment specification (type, target, sequences, params)",
    )
    experiment_url: str = Field(..., description="URL to view the experiment in the Foundry portal")
    id: str = Field(..., description="Unique identifier for the experiment")
    name: str = Field(..., description="Human-readable name for the experiment")
    results_status: ResultsStatus = Field(
        ..., description="Indicates whether results are available for this experiment"
    )
    status: ExperimentStatus = Field(..., description="Current lifecycle status of the experiment")
    stripe_invoice_id: str | None = Field(None, description="Stripe invoice ID if invoiced")
    stripe_quote_id: str | None = Field(None, description="Stripe quote ID if quote was generated")


# Result types for different experiment types


class AffinityResult(BaseModel):
    """Result for affinity experiments (BLI/SPR)."""

    sequence_id: str = Field(..., description="ID of the sequence tested")
    sequence_name: str | None = Field(None, description="Human-readable sequence name")
    target_id: str = Field(..., description="ID of the target antigen")
    n_replicates: int = Field(..., description="Number of replicates performed")
    kd: list[float] = Field(..., description="KD values per replicate (in nM)")
    kd_units: str = Field(default="nM", description="Units for KD values")
    binding_strength: str | None = Field(
        None, description="Binding strength classification: strong, moderate, weak, none"
    )
    kon: float | None = Field(None, description="Association rate constant (M⁻¹s⁻¹)")
    koff: float | None = Field(None, description="Dissociation rate constant (s⁻¹)")


class ThermostabilityResult(BaseModel):
    """Result for thermostability experiments."""

    sequence_id: str = Field(..., description="ID of the sequence tested")
    sequence_name: str | None = Field(None, description="Human-readable sequence name")
    tm: float | None = Field(None, description="Melting temperature (°C)")
    t_agg: float | None = Field(None, description="Aggregation temperature (°C)")
    t_onset: float | None = Field(None, description="Onset temperature (°C)")
    quality_score: float | None = Field(None, description="Quality score (0.0-1.0)")


# Cost breakdown types


class AssayCost(BaseModel):
    """Assay cost breakdown."""

    experiment_type: str = Field(..., description="Type of experiment")
    sequence_count: int = Field(..., description="Number of sequences")
    n_replicates: int = Field(..., description="Number of replicates")
    unit_price_cents: int = Field(..., description="Price per unit in cents")
    replicate_price_cents: int = Field(..., description="Price per replicate in cents")
    subtotal_cents: int = Field(..., description="Subtotal for assay in cents")


class MaterialCost(BaseModel):
    """Material cost breakdown."""

    target_id: str = Field(..., description="ID of the target")
    target_name: str = Field(..., description="Name of the target")
    sequence_count: int = Field(..., description="Number of sequences")
    unit_price_cents: int = Field(..., description="Price per unit in cents")
    subtotal_cents: int = Field(..., description="Subtotal for materials in cents")


class CostBreakdown(BaseModel):
    """Full cost breakdown for an experiment."""

    pricing_version: str = Field(..., description="Version of the pricing model")
    assay: AssayCost = Field(..., description="Assay cost breakdown")
    materials: MaterialCost | None = Field(None, description="Material cost breakdown")
    total_cents: int = Field(..., description="Total cost in cents")


class IncompleteCostEstimate(BaseModel):
    """Incomplete cost estimate when target lacks pricing."""

    reason: str = Field(..., description="Reason for incomplete estimate")
    missing_fields: list[str] = Field(default_factory=list, description="Missing fields")


class CostEstimateResponse(BaseModel):
    """Response from cost estimation endpoint."""

    breakdown: CostBreakdown | None = Field(None, description="Full cost breakdown if available")
    incomplete: IncompleteCostEstimate | None = Field(
        None, description="Incomplete estimate details if pricing unavailable"
    )
    warnings: list[str] = Field(default_factory=list, description="Warnings about the estimate")


# Sequence types for /sequences endpoints


class SequenceExperimentRef(BaseModel):
    """Reference to the experiment a sequence belongs to."""

    experiment_id: str = Field(..., description="Experiment UUID")
    experiment_code: str = Field(..., description="Human-readable experiment code")
    experiment_status: str | None = Field(None, description="Current experiment status")


class SequenceListItem(BaseModel):
    """Summary of a sequence in list responses."""

    id: str = Field(..., description="Unique sequence identifier")
    name: str | None = Field(None, description="Human-readable sequence name")
    fasta_preview: str | None = Field(None, description="FASTA preview of the sequence")
    length: int | None = Field(None, description="Amino acid count")
    is_control: bool = Field(default=False, description="Whether this is a control sequence")
    experiment_id: str = Field(..., description="Parent experiment ID")
    experiment_code: str = Field(..., description="Parent experiment code")
    created_at: str = Field(..., description="ISO 8601 creation timestamp")


class SequenceList(BaseModel):
    """Paginated list of sequences."""

    sequences: list[SequenceListItem] = Field(..., description="Array of sequence summaries")
    total: int = Field(..., description="Total sequences matching filters", ge=0)
    count: int = Field(..., description="Number of sequences in this response", ge=0)
    offset: int = Field(..., description="Offset used for pagination", ge=0)


class SequenceInfoModel(BaseModel):
    """Full details for a specific sequence."""

    id: str = Field(..., description="Unique sequence identifier")
    aa_string: str = Field(..., description="Complete amino acid sequence")
    length: int = Field(..., description="Amino acid count")
    name: str | None = Field(None, description="Human-readable sequence name")
    is_control: bool = Field(default=False, description="Whether this is a control sequence")
    experiment: SequenceExperimentRef = Field(..., description="Parent experiment reference")
    created_at: str = Field(..., description="ISO 8601 creation timestamp")
    metadata: dict[str, Any] | None = Field(None, description="Structural metadata")
    customer_preferences: dict[str, Any] | None = Field(None, description="Customer preferences")


class SequenceEntry(BaseModel):
    """Sequence entry for creating/appending sequences."""

    aa_string: str = Field(..., description="Amino acid sequence")
    name: str | None = Field(None, description="Human-readable sequence name")
    control: bool | None = Field(None, description="Mark as control well")
    metadata: dict[str, Any] | None = Field(None, description="Structural metadata")
    customer_preferences: dict[str, Any] | None = Field(None, description="Customer preferences")


class SequenceAddRequest(BaseModel):
    """Request to append sequences to a draft experiment."""

    experiment_code: str = Field(..., description="Human-readable experiment code")
    sequences: list[SequenceEntry] = Field(..., description="Sequences to add")


class SequenceAddResponse(BaseModel):
    """Response from appending sequences."""

    added_count: int = Field(..., description="Number of sequences added")
    experiment_id: str = Field(..., description="Experiment UUID")
    experiment_code: str = Field(..., description="Human-readable experiment code")
    sequence_ids: list[str] = Field(..., description="UUIDs of added sequences")


# Result types for /results endpoints


class ResultSummaryAffinity(BaseModel):
    """Affinity result summary within a result."""

    sequence_id: str = Field(..., description="Sequence ID tested")
    sequence_name: str | None = Field(None, description="Human-readable sequence name")
    target_id: str = Field(..., description="Target antigen ID")
    n_replicates: int = Field(..., description="Number of replicates performed")
    kd: list[float] = Field(..., description="KD values per replicate (nM)")
    kd_units: str = Field(default="nM", description="Units for KD values")
    kon: float | None = Field(None, description="Association rate constant (M⁻¹s⁻¹)")
    koff: float | None = Field(None, description="Dissociation rate constant (s⁻¹)")
    binding_strength: str | None = Field(None, description="Qualitative binding assessment")


class ResultSummaryThermostability(BaseModel):
    """Thermostability result summary within a result."""

    sequence_id: str = Field(..., description="Sequence ID tested")
    sequence_name: str | None = Field(None, description="Human-readable sequence name")
    tm: float | None = Field(None, description="Melting temperature (°C)")
    t_agg: float | None = Field(None, description="Aggregation temperature (°C)")
    t_onset: float | None = Field(None, description="Unfolding onset temperature (°C)")
    quality_score: float | None = Field(None, description="Quality score (0.0-1.0)")


class ResultListItem(BaseModel):
    """Summary of a result in list responses."""

    id: str = Field(..., description="Unique result identifier")
    title: str = Field(..., description="Result title")
    experiment_id: str = Field(..., description="Parent experiment ID")
    result_type: str = Field(..., description="Result type: affinity or thermostability")
    created_at: str = Field(..., description="ISO 8601 creation timestamp")


class ResultInfoModel(BaseModel):
    """Full details for a specific result."""

    id: str = Field(..., description="Unique result identifier")
    title: str = Field(..., description="Result title")
    experiment_id: str = Field(..., description="Parent experiment ID")
    result_type: str = Field(..., description="Result type: affinity or thermostability")
    created_at: str = Field(..., description="ISO 8601 creation timestamp")
    summary: list[dict[str, Any]] = Field(
        default_factory=list,
        description="Result summaries (AffinityResult or ThermostabilityResult)",
    )
    data_package_url: str | None = Field(
        None, description="Pre-signed URL for data package (valid 24hr)"
    )
    metadata: dict[str, Any] | None = Field(None, description="Author, version, methodology")


class ResultList(BaseModel):
    """Paginated list of results."""

    results: list[ResultListItem] = Field(..., description="Array of result summaries")
    total: int = Field(..., description="Total results matching filters", ge=0)
    count: int = Field(..., description="Number of results in this response", ge=0)
    offset: int = Field(..., description="Offset used for pagination", ge=0)
