# generated by datamodel-codegen:
#   filename:  https://foundry-api-public.adaptyvbio.com/api/v1/openapi.json
#   timestamp: 2026-06-03T21:16:39+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, RootModel


class AAString(RootModel[str]):
    root: str = Field(
        ...,
        description='A validated amino acid sequence string.\n\nContains only the 20 natural amino acids (single-letter codes: A, C, D, E,\nF, G, H, I, K, L, M, N, P, Q, R, S, T, V, W, Y) and colons for multichain\nnotation. Input is case-insensitive; stored uppercase.\n\nMultichain sequences use colon separators (e.g., `MVLS:EVQL` for a\ntwo-chain construct). Invalid characters or empty strings are rejected.',
        examples=['EVQLVESGGGLVQPGGSLRLSCAAS'],
    )


class AffinityReplicate(BaseModel):
    binding_strength: str | None = Field(
        None, description='Qualitative binding assessment for this replicate'
    )
    kd: float | None = Field(
        None, description='Equilibrium dissociation constant (M), if measurable'
    )
    koff: float | None = Field(
        None, description='Dissociation rate constant (s⁻¹), if measurable'
    )
    koff_method: str | None = Field(
        None, description='Fitting model used for koff (e.g. "1:1", "2:1")'
    )
    kon: float | None = Field(
        None, description='Association rate constant (M⁻¹s⁻¹), if measurable'
    )
    kon_method: str | None = Field(
        None, description='Fitting model used for kon (e.g. "1:1", "2:1")'
    )
    replicate: int = Field(..., description='Replicate index (1-based)')


class AssayCost(BaseModel):
    experiment_type: str = Field(
        ...,
        description='Experiment type (e.g., "screening", "affinity", "thermostability",\n"fluorescence", "expression")',
        examples=['screening'],
    )
    n_replicates: int = Field(
        ..., description='Number of technical replicates', examples=[3], ge=0
    )
    replicate_price_cents: int = Field(
        ...,
        description='Price per additional replicate (beyond first) in USD cents.\nZero for experiment types without replicate pricing.',
        examples=[2900],
    )
    sequence_count: int = Field(
        ..., description='Number of sequences in the experiment', examples=[5], ge=0
    )
    subtotal_cents: int = Field(
        ...,
        description='Subtotal for assay costs in USD cents.\nCalculated as: `sequence_count × (unit_price + max(0, n_replicates - 1) × replicate_price)`',
        examples=[103500],
    )
    unit_price_cents: int = Field(
        ...,
        description='Base price per sequence in USD cents.\nIncludes the first replicate.',
        examples=[14900],
    )


class AttenuateTokenResponse(BaseModel):
    id: str = Field(
        ...,
        description='Database ID of the attenuated token record (for revocation/management).',
    )
    token: str = Field(
        ...,
        description='The attenuated token string. Format: `abs0_{slug}{biscuit_base64}`.',
    )


class AttenuationSpec(BaseModel):
    allowed_actions: list[str] | None = Field(
        None,
        description='Explicit list of permitted operations.\n\nValues: `list`, `read`, `create`, `update`, `delete`, `issue`, `revoke`, `mint_token`\n\nIf specified, only these operations are allowed. Applied alongside `read_only` and\n`non_destructive`; effective permissions are the intersection of all constraints.',
    )
    allowed_org_ids: list[str] | None = Field(
        None,
        description="Restrict token to only these organization IDs.\n\nThe token must already have access to these orgs; attenuation cannot expand\naccess. The token's append-only property enforces this cryptographically.",
    )
    allowed_resources: list[str] | None = Field(
        None,
        description='Explicit list of permitted resource types.\n\nCommon values: `experiment`, `sequence`, `target`, `result`, `project`, `organization`, `user`, `token`, `webhook`, `update`, `quote`, `invoice`, `billing`, `feedback`, `partner`, `credit`, `usage`, `product`, `info`, `admin`, `policy`\n\nIf specified, the token can only access these resource types.',
    )
    expires_at: str | None = Field(
        None,
        description='Shorten token expiration to this timestamp (cannot extend past original expiry).\n\nFormat: ISO 8601 / RFC 3339 (e.g., "2026-01-20T00:00:00Z")',
    )
    non_destructive: bool | None = Field(
        None,
        description='Allow all operations except destructive ones (delete).\n\nWhen enabled, the token can list, read, create, and update but not delete.',
    )
    read_only: bool | None = Field(
        None,
        description='Restrict to list and read operations only.\n\nWhen enabled, the token cannot create, update, or delete resources.',
    )


class Bioactivity(BaseModel):
    bli: bool = Field(
        ..., description='BLI (biolayer interferometry) data available from vendor'
    )
    elisa: bool = Field(..., description='ELISA bioactivity data available from vendor')
    spr: bool = Field(
        ..., description='SPR (surface plasmon resonance) data available from vendor'
    )


class ConfirmQuoteRequest(BaseModel):
    notes: str | None = Field(
        None,
        description='Reserved for future use. Currently accepted but not acted upon.',
        examples=['Please expedite processing'],
    )
    purchase_order_number: str | None = Field(
        None,
        description='Purchase order number from your organization (optional)',
        examples=['PO-2026-00142'],
    )


class CreateCustomTargetRequest(BaseModel):
    molecular_weight: float | None = Field(
        None, description='Molecular weight in kilodaltons (kDa)', examples=[15.5]
    )
    name: str = Field(
        ..., description='Display name for the target', examples=['My Custom Antigen']
    )
    note: str | None = Field(
        None,
        description='Additional notes or context about the target',
        examples=['Expressed in HEK293 cells'],
    )
    pdb_file: str | None = Field(
        None,
        description='Base64-encoded PDB file content for custom structures not in the PDB',
    )
    pdb_id: str | None = Field(
        None,
        description='PDB database identifier (e.g., "1ABC", "6LU7")',
        examples=['1HHO'],
    )
    product_id: str = Field(
        ...,
        description='User-provided identifier, must be unique within your organization',
        examples=['CUSTOM-001'],
    )
    product_url: str | None = Field(
        None,
        description='URL to vendor product page or documentation',
        examples=['https://www.acrobiosystems.com/product/PD1'],
    )
    sequence: str | None = Field(
        None,
        description='Amino acid sequence using standard single-letter codes (A-Z excluding B, J, X, Z).\nSupports standard 20 amino acids plus selenocysteine (U) and pyrrolysine (O).',
        examples=['MVLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHFDLSH'],
    )
    vendor: str | None = Field(
        None,
        description='Source vendor name if applicable',
        examples=['ACRO Biosystems'],
    )


class CreateExpResponse(BaseModel):
    error: str | None = Field(
        None,
        description='Error message when the request fails validation or processing',
    )
    experiment_id: str = Field(
        ..., description='Unique identifier assigned to the new experiment'
    )
    stripe_hosted_invoice_url: str | None = Field(
        None,
        description='Stripe hosted invoice page. When the invoice is unpaid this is the\ncheckout/payment page; after payment it becomes a receipt viewer.',
    )
    stripe_invoice_id: str | None = Field(
        None,
        description='Stripe invoice ID, present when `auto_accept_quote` created an invoice.',
    )


class CustomTargetRequestStatus(StrEnum):
    pending_review = 'pending_review'
    approved = 'approved'
    rejected = 'rejected'


class ErrorResponse(BaseModel):
    error: str = Field(
        ...,
        description='Human-readable error description.',
        examples=['experiment not found'],
    )
    request_id: str = Field(
        ...,
        description='Request identifier for support correlation (also in `x-request-id` header).',
        examples=['req_019462a4-b1c2-7def-8901-23456789abcd'],
    )


class Type(StrEnum):
    estimate = 'estimate'


class Type1(StrEnum):
    incomplete_estimate = 'incomplete_estimate'


class Type2(StrEnum):
    quoted = 'quoted'


class Type3(StrEnum):
    invoiced = 'invoiced'


class ExperimentStatus(StrEnum):
    draft = 'draft'
    waiting_for_confirmation = 'waiting_for_confirmation'
    canceled = 'canceled'
    waiting_for_materials = 'waiting_for_materials'
    in_production = 'in_production'
    quote_sent = 'quote_sent'
    in_queue = 'in_queue'
    data_analysis = 'data_analysis'
    in_review = 'in_review'
    done = 'done'


class ExperimentType(StrEnum):
    affinity = 'affinity'
    screening = 'screening'
    thermostability = 'thermostability'
    fluorescence = 'fluorescence'
    expression = 'expression'
    epitope_binning = 'epitope_binning'
    enzyme_activity = 'enzyme_activity'


class FeedbackType(StrEnum):
    feature_request = 'feature_request'
    feedback = 'feedback'
    bug_report = 'bug_report'


class FrameworkRegions(BaseModel):
    ch: str | None = Field(
        None,
        description='Constant heavy chain (CH1) region sequence.\n\nTypically the human IgG1 CH1 domain (~100 amino acids).',
        examples=[
            'ASTKGPSVFPLAPSSKSTSGGTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKKVEPKSC'
        ],
    )
    cl: str | None = Field(
        None,
        description='Constant light chain (CL) region sequence.\n\nEither kappa (~60% of human antibodies) or lambda (~40%).',
        examples=[
            'RTVAAPSVFIFPPSDEQLKSGTASVVCLLNNFYPREAKVQWKVDNALQSGNSQESVTEQDSKDSTYSLSSTLTLSKADYEKHKVYACEVTHQGLSSPVTKSFNRGEC'
        ],
    )


class HealthDbResponse(BaseModel):
    db: str = Field(
        ..., description='Database connectivity: "connected" or "unreachable".'
    )
    status: str = Field(..., description='Service status: "ok" or "degraded".')


class HealthResponse(BaseModel):
    status: str = Field(
        ..., description='Service status: "ok" when the service is alive.'
    )


class LotAllocation(BaseModel):
    lot_price_cents: int = Field(
        ..., description='Price of one unit of this lot in USD cents', examples=[80000]
    )
    lot_size_ug: float = Field(
        ..., description='Size of this lot in micrograms', examples=[200.0]
    )
    quantity: int = Field(
        ..., description='Number of this lot needed', examples=[2], ge=0
    )


class LotPriceTier(BaseModel):
    num_sequences: int = Field(
        ..., description='Maximum sequences this lot can serve', examples=[33], ge=0
    )
    price_usdcent: int = Field(
        ..., description='Full lot price in USD cents', examples=[30000]
    )


class Type4(StrEnum):
    per_sequence = 'per_sequence'


class MaterialCost1(BaseModel):
    price_per_sequence_cents: int = Field(
        ..., description='Price per sequence in USD cents', examples=[500]
    )
    sequence_count: int = Field(
        ..., description='Number of sequences requiring material', examples=[5], ge=0
    )
    subtotal_cents: int = Field(
        ...,
        description='Subtotal: sequence_count * price_per_sequence_cents',
        examples=[2500],
    )
    target_id: str = Field(
        ..., description='Target identifier (e.g., "PD1-H5229")', examples=['PD1-H5229']
    )
    target_name: str = Field(
        ...,
        description='Human-readable target name (e.g., "Human PD-L1")',
        examples=['Human PD-L1'],
    )
    type: Type4


class Type5(StrEnum):
    per_broken_lot = 'per_broken_lot'


class MaterialCost2(BaseModel):
    lots: list[LotAllocation] = Field(
        ..., description='Lot allocations covering the order'
    )
    sequence_count: int = Field(
        ..., description='Number of sequences in the experiment', examples=[10], ge=0
    )
    subtotal_cents: int = Field(
        ...,
        description='Total material cost in USD cents (sum of lot_price_cents × quantity)',
        examples=[30000],
    )
    target_id: str = Field(..., description='Target identifier', examples=['IL6-H5268'])
    target_name: str = Field(
        ..., description='Human-readable target name', examples=['Human IL-6']
    )
    type: Type5


class MaterialCost(RootModel[MaterialCost1 | MaterialCost2]):
    root: MaterialCost1 | MaterialCost2 = Field(
        ...,
        description='Material cost for target antigens, discriminated by pricing model.',
    )


class MaterialsUnavailable(BaseModel):
    reason: str = Field(
        ...,
        description='Human-readable explanation for why pricing is unavailable',
        examples=[
            "Human PD-L1 is not yet onboarded to self-service pricing. You'll receive a quote with full price information."
        ],
    )
    target_id: str = Field(
        ...,
        description='Target identifier that lacks pricing configuration',
        examples=['c383cc1d-fe22-5dbf-953c-378bc073019d'],
    )
    target_name: str | None = Field(
        None,
        description='Human-readable target name (fetched from catalog, if available)',
        examples=['Human PD-L1'],
    )


class Method(StrEnum):
    bli = 'bli'
    spr = 'spr'


class ModifyExpResponse(BaseModel):
    id: str = Field(..., description='Experiment identifier that was modified')
    message: str | None = Field(
        None, description='Optional message, e.g., if modification is not allowed'
    )
    updated: bool = Field(..., description='Indicates if any changes were applied')


class PdbEntry(BaseModel):
    id: str = Field(
        ...,
        description='PDB ID from RCSB Protein Data Bank (e.g., "5JDR")',
        examples=['5JDR'],
    )
    url: str = Field(
        ...,
        description='Direct download URL for the PDB file',
        examples=['https://files.rcsb.org/download/5JDR.pdb'],
    )


class QuoteCreationErrorKind(StrEnum):
    customer_quote_cap = 'customer_quote_cap'
    rate_limited = 'rate_limited'
    upstream_server_error = 'upstream_server_error'
    missing_customer = 'missing_customer'
    missing_product = 'missing_product'
    other = 'other'


class QuoteLineItem(BaseModel):
    description: str = Field(
        ..., description='Description of the item or service being quoted'
    )
    quantity: int = Field(..., description='Number of units')
    total_cents: int = Field(
        ...,
        description='Total amount for this line item in smallest currency unit (cents)',
    )
    unit_price_cents: int = Field(
        ..., description='Price per unit in smallest currency unit (cents)'
    )


class QuoteRejectionReason(StrEnum):
    price = 'price'
    scope = 'scope'
    timeline = 'timeline'
    budget = 'budget'
    other = 'other'


class RejectQuoteRequest(BaseModel):
    feedback: str | None = Field(
        None,
        description='Additional feedback or specific concerns (optional but helpful)',
        examples=['Budget constraints require a 15% reduction'],
    )
    reason: QuoteRejectionReason = Field(
        ..., description='Primary reason for rejection'
    )


class ResultType(StrEnum):
    affinity = 'affinity'


class ResultType1(StrEnum):
    thermostability = 'thermostability'


class ResultsStatus(StrEnum):
    none = 'none'
    partial = 'partial'
    all = 'all'


class RevokeTokenResponse(BaseModel):
    children_revoked: int = Field(
        ...,
        description='Number of attenuated child tokens that were newly revoked in this call.\nWill be 0 on idempotent repeated calls (children already stamped).',
        examples=[3],
    )
    revoked_at: str = Field(
        ...,
        description='Timestamp when the token was revoked (may be earlier if already revoked).',
    )
    token_id: str = Field(
        ...,
        description='The root token_id that was revoked (all descendants are also revoked).',
        examples=['550e8400-e29b-41d4-a716-446655440000'],
    )


class SequenceAddResponse(BaseModel):
    added_count: int = Field(..., description='Number of sequences added', ge=0)
    experiment_code: str = Field(..., description='Human-readable experiment code')
    experiment_id: str = Field(..., description='UUID of the experiment')
    sequence_ids: list[str] = Field(
        ..., description='UUIDs of the newly created sequences'
    )


class SequenceEntry(BaseModel):
    aa_string: AAString = Field(
        ...,
        description='Protein/peptide sequence in standard single-letter amino acid format.\n\nValid characters: A,C,D,E,F,G,H,I,K,L,M,N,P,Q,R,S,T,V,W,Y and colon for multichain.',
    )
    control: bool | None = Field(
        None, description='Whether the sequence should be treated as a control well'
    )
    metadata: Any | None = Field(
        None,
        description='Arbitrary metadata supplied by the customer (tag locations, notes)',
    )
    name: str | None = Field(
        None,
        description='Optional name for the sequence (e.g., "mAb1", "scFv-001")',
        examples=['mAb1'],
    )


class SequenceExperimentRef(BaseModel):
    experiment_code: str = Field(..., description='Human-readable experiment code')
    experiment_id: str = Field(..., description='Unique identifier for the experiment')
    experiment_status: str | None = Field(
        None, description='Current status of the experiment'
    )


class SequenceInfo(BaseModel):
    aa_string: str | None = Field(None, description='Complete amino acid sequence')
    created_at: str = Field(..., description='When the sequence was created')
    experiment: SequenceExperimentRef = Field(
        ..., description='Experiment containing this sequence'
    )
    id: str = Field(..., description='Unique identifier for the sequence')
    is_control: bool = Field(
        ..., description='Whether this sequence is marked as a control'
    )
    length: int = Field(..., description='Sequence length in amino acids', ge=0)
    metadata: Any | None = Field(
        None,
        description='Sequence-level annotations from the analysis pipeline.\n\nWhen present, may include chain assignments and framework region\nboundaries for antibody sequences. Structure varies by experiment type.',
    )
    name: str | None = Field(None, description='Optional name assigned to the sequence')


class SequenceType(StrEnum):
    sc_fv = 'ScFv'
    fab = 'FAB'
    single_chain = 'SingleChain'
    ig_g = 'IgG'


class String(RootModel[str]):
    root: str


class StripeInvoiceStatus(StrEnum):
    draft = 'draft'
    open = 'open'
    paid = 'paid'
    void = 'void'
    uncollectible = 'uncollectible'


class StripeQuoteStatus(StrEnum):
    draft = 'draft'
    open = 'open'
    accepted = 'accepted'
    canceled = 'canceled'
    stale = 'stale'


class SubmitConflictError(BaseModel):
    error: str = Field(
        ...,
        description='Human-readable message (matches `ErrorResponse.error`).',
        examples=['Cannot submit draft experiment: Stripe quote creation failed.'],
    )
    error_kind: QuoteCreationErrorKind | None = None
    hint: str | None = Field(
        None,
        description='Operator-facing hint corresponding to `error_kind`, or `null`.',
        examples=[
            "Stripe rejected the quote: this organization's customer has reached the draft-quote cap. Contact admin to cancel stale test-mode quotes."
        ],
    )
    request_id: str = Field(
        ...,
        description='Request correlation id (matches `ErrorResponse.request_id`).',
        examples=['req_019462a4-b1c2-7def-8901-23456789abcd'],
    )


class SubmitFeedbackRequest(BaseModel):
    feedback_type: FeedbackType = Field(..., description='Feedback category.')
    human_note: str | None = Field(
        None,
        description='Human-readable text note (optional, can be combined with json_body).',
        examples=['Got 500 error when creating experiment'],
    )
    json_body: Any | None = Field(
        None,
        description='Structured JSON details (optional, can be combined with human_note).',
    )
    request_uuid: str = Field(
        ...,
        description='UUID of the request that prompted this feedback.',
        examples=['01900abc-1234-7890-1234-567890abcdef'],
    )
    title: str | None = Field(
        None,
        description='Optional short title. If omitted or blank, a default is used.',
        examples=['Timeout when creating experiment'],
    )


class SubmitFeedbackResponse(BaseModel):
    message: str = Field(..., description='Confirmation message.')
    reference: str = Field(
        ...,
        description='Feedback reference for future correspondence.',
        examples=['a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2'],
    )


class TagLocation(StrEnum):
    n = 'N'
    c = 'C'


class TargetDetails(BaseModel):
    bioactivity: Bioactivity | None = None
    description: str | None = Field(None, description='Vendor product description.')
    expression_system: str | None = Field(
        None,
        description='Expression system used to produce the target (e.g., "HEK293").',
        examples=['HEK293'],
    )
    family: str | None = Field(
        None,
        description='Protein family classification (e.g., "Immunoglobulin superfamily").',
        examples=['Immunoglobulin superfamily'],
    )
    gene_names: list[str] | None = Field(
        None,
        description='Gene names/symbols. First entry is canonical (e.g., ["PDCD1", "PD1"]).',
        examples=[['PDCD1', 'PD1']],
    )
    molecular_weight: str | None = Field(
        None,
        description='Raw molecular weight string from the vendor catalog (e.g., "23.1 kDa").',
        examples=['23.1 kDa'],
    )
    ncbi_id: str | None = Field(
        None,
        description='NCBI accession ID. Complementary to `uniprot_id` — mostly viral targets.',
        examples=['NP_005009'],
    )
    organism: str | None = Field(
        None,
        description='Source organism (e.g., "Homo sapiens", "SARS-CoV-2").',
        examples=['Human'],
    )
    purity: float | None = Field(
        None,
        description='Purity percentage (0-100). Vendor-dependent, only ~20% of targets.',
        examples=[95.0],
    )
    sequence: str | None = Field(
        None, description='Amino acid sequence of the target protein.'
    )
    sequence_length: int | None = Field(
        None,
        description='Amino acid count (avoids client-side counting of `sequence`).',
        examples=[288],
    )
    structures: list[PdbEntry] | None = Field(
        None,
        description='PDB structures with download URLs. Each entry pairs a PDB ID\nwith its RCSB download URL.',
        examples=[[{'id': '5JDR', 'url': 'https://files.rcsb.org/download/5JDR.pdb'}]],
    )
    subcellular_locations: list[str] | None = Field(
        None,
        description='Known subcellular locations (e.g., ["Cell membrane", "Secreted"]).',
        examples=[['Cell membrane']],
    )
    synonyms: list[str] | None = Field(
        None,
        description='Alternative protein names (e.g., ["Programmed cell death protein 1", "CD279"]).',
    )
    tags: list[str] | None = Field(
        None,
        description='Purification/fusion tags on the product (e.g., ["His"], ["Fc"]).',
        examples=[['His']],
    )


class Type6(StrEnum):
    per_sequence = 'per_sequence'


class TargetPricing1(BaseModel):
    price_per_sequence_cents: int = Field(
        ..., description='Material cost per sequence in USD cents', examples=[500]
    )
    type: Type6


class Type7(StrEnum):
    per_broken_lot = 'per_broken_lot'


class TargetPricing2(BaseModel):
    lot_prices: list[LotPriceTier] = Field(
        ..., description='Lot price tiers, sorted by num_sequences ascending'
    )
    type: Type7


class TargetPricing(RootModel[TargetPricing1 | TargetPricing2]):
    root: TargetPricing1 | TargetPricing2 = Field(
        ...,
        description="Pricing information for a target's material costs.\n\nDetermines how material costs are calculated for an experiment using this target.\nThe variant reflects the pricing model configured in `foundry_api.product_prices`.",
    )


class ThermostabilityResult(BaseModel):
    quality_score: float | None = Field(
        None, description='Quality score from analysis pipeline (0.0-1.0)'
    )
    sequence_id: str = Field(
        ..., description='Sequence identifier from experiment submission'
    )
    sequence_name: str | None = Field(
        None, description='Optional sequence name provided during submission'
    )
    t_agg: float | None = Field(
        None, description='Aggregation temperature from scattering curve (Celsius)'
    )
    t_onset: float | None = Field(
        None, description='Onset temperature marking start of unfolding (Celsius)'
    )
    tm: float | None = Field(
        None, description='Melting temperature from 350nm/330nm ratio curve (Celsius)'
    )


class AffinityResult(BaseModel):
    binding_strength: str = Field(
        ...,
        description='Qualitative binding assessment (e.g., "strong", "medium", "weak", "none")',
    )
    kd_log_std: float | None = Field(
        None, description='Log standard deviation of KD across replicates'
    )
    kd_mean: float | None = Field(
        None, description='Mean equilibrium dissociation constant (M) across replicates'
    )
    kd_units: str = Field(
        ...,
        description='Units for KD measurements — values from the database are in molar (M)',
    )
    koff_log_std: float | None = Field(
        None, description='Log standard deviation of koff across replicates'
    )
    koff_mean: float | None = Field(
        None, description='Mean dissociation rate constant (s⁻¹) across replicates'
    )
    kon_log_std: float | None = Field(
        None, description='Log standard deviation of kon across replicates'
    )
    kon_mean: float | None = Field(
        None, description='Mean association rate constant (M⁻¹s⁻¹) across replicates'
    )
    replicates: list[AffinityReplicate] = Field(
        ..., description='Per-replicate kinetic measurements with method info'
    )
    sequence: SequenceEntry = Field(
        ..., description='Antibody sequence that was evaluated'
    )
    target_id: str = Field(
        ..., description='Target antigen identifier from Adaptyvbio catalog'
    )


class AttenuateTokenRequest(BaseModel):
    attenuated_parent_token_id: str | None = Field(
        None,
        description='If attenuating an already-attenuated token (chained attenuation),\nprovide the `id` of the parent attenuated token record. Omit when\nattenuating a root token directly.',
    )
    attenuation: AttenuationSpec = Field(
        ..., description='Restrictions to apply to the token.'
    )
    name: str = Field(
        ...,
        description='Human-readable label for this attenuated token.\n\nNames are not unique — they are purely for display purposes.',
    )
    token: str = Field(
        ...,
        description='Existing token string (format: `abs0_{slug}{biscuit_base64}`) to attenuate.',
    )


class ConfirmQuoteResponse(BaseModel):
    hosted_invoice_url: str | None = Field(
        None,
        description='Stripe-hosted URL where the customer can view and pay the generated invoice',
        examples=['https://invoice.stripe.com/i/acct_1234/test_5678'],
    )
    id: str = Field(..., description='Quote ID that was accepted')
    invoice_id: str | None = Field(
        None, description='ID of the invoice generated from this quote (if applicable)'
    )
    status: StripeQuoteStatus = Field(
        ..., description='New status (accepted after confirmation)'
    )


class CostBreakdown(BaseModel):
    assay: AssayCost = Field(..., description='Assay-related costs')
    materials: MaterialCost | None = None
    pricing_version: String = Field(
        ..., description='Pricing version applied (e.g., "v1_2026-01-20")'
    )
    total_cents: int = Field(
        ..., description='Total estimated cost in USD cents', examples=[106000]
    )


class CreateCustomTargetResponse(BaseModel):
    created_at: str = Field(
        ..., description='ISO 8601 timestamp when the request was created'
    )
    id: str = Field(..., description='Unique identifier assigned to the request')
    status: CustomTargetRequestStatus = Field(
        ..., description='Current status (always "pending_review" for new submissions)'
    )


class CustomTargetRequestInfo(BaseModel):
    created_at: str = Field(
        ..., description='ISO 8601 timestamp when the request was created'
    )
    id: str = Field(..., description='Unique identifier for the request')
    material_id: str | None = Field(
        None, description='Material ID if the request was approved and linked'
    )
    molecular_weight: float | None = Field(
        None, description='Molecular weight in kDa if provided'
    )
    name: str = Field(..., description='Display name of the target')
    note: str | None = Field(None, description='User notes')
    pdb_file: str | None = Field(
        None, description='Base64-encoded PDB file if provided'
    )
    pdb_id: str | None = Field(None, description='PDB database identifier if provided')
    product_id: str = Field(..., description='User-provided product identifier')
    product_url: str | None = Field(None, description='Vendor product URL')
    sequence: str | None = Field(None, description='Amino acid sequence if provided')
    status: CustomTargetRequestStatus = Field(..., description='Current review status')
    updated_at: str = Field(
        ..., description='ISO 8601 timestamp when the request was last updated'
    )
    vendor: str | None = Field(None, description='Vendor name')


class ExperimentConfirmationResponse(BaseModel):
    confirmed_at: str = Field(
        ...,
        description='RFC3339 timestamp when confirmation completed',
        examples=['2026-02-15T14:30:00Z'],
    )
    experiment_id: str = Field(
        ...,
        description='Experiment identifier',
        examples=['019462a4-b1c2-7def-8901-23456789abcd'],
    )
    previous_status: ExperimentStatus = Field(
        ..., description='Status before the transition'
    )
    status: ExperimentStatus = Field(..., description='Status after the transition')
    stripe_invoice_url: str | None = Field(
        None,
        description='Hosted invoice URL from Stripe (available after WaitingForConfirmation → WaitingForMaterials)',
        examples=['https://invoice.stripe.com/i/acct_1234/test_5678'],
    )


class ExperimentCosts1(BaseModel):
    breakdown: CostBreakdown = Field(..., description='Detailed cost breakdown')
    type: Type


class ExperimentCosts2(BaseModel):
    assay: AssayCost = Field(..., description='Assay costs (always calculable)')
    materials_unavailable: MaterialsUnavailable = Field(
        ..., description='Explanation for missing materials pricing'
    )
    pricing_version: String = Field(
        ..., description='Pricing version applied (e.g., "v1_2026-01-20")'
    )
    total_cents: Any
    type: Type1


class ExperimentCosts3(BaseModel):
    amount_cents: int = Field(
        ...,
        description='Quote amount in smallest currency unit (cents)',
        examples=[106000],
    )
    currency: str = Field(..., description='Currency code (ISO 4217)', examples=['usd'])
    expires_at: str | None = Field(
        None,
        description='Quote expiration timestamp (ISO 8601).\nOmitted if the quote has no expiration.',
        examples=['2026-02-20T12:00:00Z'],
    )
    status: StripeQuoteStatus = Field(..., description='Quote status from Stripe')
    stripe_quote_url: str = Field(
        ...,
        description='Direct link to the quote in the Stripe Dashboard',
        examples=['https://dashboard.stripe.com/quotes/qt_1234567890'],
    )
    type: Type2


class ExperimentCosts4(BaseModel):
    amount_cents: int = Field(
        ...,
        description='Invoice amount in smallest currency unit (cents)',
        examples=[106000],
    )
    currency: str = Field(..., description='Currency code (ISO 4217)', examples=['usd'])
    status: StripeInvoiceStatus = Field(..., description='Invoice status from Stripe')
    stripe_invoice_url: str | None = Field(
        None,
        description='Hosted invoice payment URL from Stripe.\nOmitted if not available (e.g., draft invoices).',
        examples=['https://invoice.stripe.com/i/acct_abc/test_xyz'],
    )
    type: Type3


class ExperimentCosts(
    RootModel[ExperimentCosts1 | ExperimentCosts2 | ExperimentCosts3 | ExperimentCosts4]
):
    root: ExperimentCosts1 | ExperimentCosts2 | ExperimentCosts3 | ExperimentCosts4 = (
        Field(
            ...,
            description='Dynamic cost information for an experiment.\n\nRepresents the current cost state based on experiment lifecycle:\n- `Estimate`: Computed from experiment spec (no Stripe quote yet)\n- `Quoted`: Real quote from Stripe (awaiting acceptance)\n- `Invoiced`: Invoice created (payment pending or complete)\n\nResolution order: If `stripe_invoice_url` exists, returns `Invoiced`. Otherwise,\nif `stripe_quote_url` exists, returns `Quoted`. Otherwise computes `Estimate`.',
        )
    )


class ExperimentInvoiceResponse(BaseModel):
    experiment_id: str = Field(..., description='Experiment identifier')
    status: StripeInvoiceStatus | None = None
    stripe_invoice_url: str | None = Field(
        None, description='Hosted invoice URL from Stripe'
    )


class ExperimentQuoteResponse(BaseModel):
    amount_subtotal: int = Field(
        ...,
        description='Subtotal amount (in the smallest currency unit)',
        examples=[500000],
    )
    amount_total: int = Field(
        ...,
        description='Total amount (in the smallest currency unit)',
        examples=[500000],
    )
    currency: str = Field(
        ..., description='ISO currency code (e.g., "usd")', examples=['usd']
    )
    experiment_id: str = Field(
        ...,
        description='Experiment identifier',
        examples=['019462a4-b1c2-7def-8901-23456789abcd'],
    )
    expires_at: str | None = Field(
        None,
        description='RFC3339 timestamp for when the quote expires (if provided by Stripe)',
        examples=['2026-03-15T23:59:59Z'],
    )
    status: StripeQuoteStatus = Field(..., description='Stripe quote status')
    stripe_quote_url: str = Field(
        ...,
        description='Quote reference URL (may require provider account access).',
        examples=['https://billing.example.com/quotes/qt_1234567890'],
    )
    updated_at: str | None = Field(
        None,
        description='RFC3339 timestamp for the last update time',
        examples=['2026-02-15T14:30:00Z'],
    )


class IncompleteCostEstimate(BaseModel):
    assay: AssayCost = Field(..., description='Assay costs (always calculable)')
    materials_unavailable: MaterialsUnavailable = Field(
        ..., description='Explanation for missing materials pricing'
    )
    pricing_version: String = Field(
        ..., description='Pricing version applied (e.g., "v1_2026-01-20")'
    )
    total_cents: Any


class ModifyExpRequest(BaseModel):
    antigen_concentrations: list[float] | None = Field(
        None, description='Update antigen concentrations (only if not fulfilled)'
    )
    description: str | None = Field(None, description='Update experiment description')
    n_replicates: int | None = Field(
        None, description='Update replicate count (only if not fulfilled)', ge=0
    )
    name: str | None = Field(None, description='Update experiment name')
    parameters: Any | None = Field(
        None,
        description='Update experiment parameters (restrictions may apply, only if not fulfilled)',
    )
    sequences: list[SequenceEntry] | None = Field(
        None, description='Replace sequence list (only if not fulfilled)'
    )
    target_id: str | None = Field(
        None,
        description='Update target identifier (only if not fulfilled).\n\n- Omitted: keep current target\n- `null`: remove target (deletes requested_materials and agreed_on_materials)\n- `"uuid"`: change to new target (performs catalog lookup, updates materials, autolinks)',
    )
    webhook_url: str | None = Field(
        None, description='Update the webhook URL for notifications'
    )


class QuoteInfo(BaseModel):
    created_at: str = Field(
        ..., description='ISO 8601 timestamp when quote was created'
    )
    currency: str = Field(..., description='ISO 4217 currency code')
    id: str = Field(..., description='Unique quote identifier')
    line_items: list[QuoteLineItem] = Field(
        ..., description='Itemized list of products/services being quoted'
    )
    notes: str = Field(
        ..., description='Additional notes or special pricing information'
    )
    organization_id: str = Field(
        ..., description='Organization ID that this quote is prepared for'
    )
    organization_name: str = Field(
        ..., description='Name of the organization receiving the quote'
    )
    quote_number: str = Field(
        ..., description='Human-readable quote number for reference'
    )
    status: StripeQuoteStatus = Field(
        ..., description='Current quote status from Stripe'
    )
    stripe_quote_url: str = Field(
        ...,
        description='Quote reference URL (may require provider account access).',
        examples=['https://billing.example.com/quotes/qt_1234567890'],
    )
    subtotal_cents: int = Field(
        ...,
        description='Sum of all line items before tax, in smallest currency unit (cents)',
    )
    tax_cents: int = Field(
        ...,
        description='Estimated tax amount in smallest currency unit (cents); may be adjusted on final invoice',
    )
    terms_and_conditions: str = Field(
        ..., description='Legal terms and conditions for this quote'
    )
    total_cents: int = Field(
        ...,
        description='Total quoted amount (subtotal + tax) in smallest currency unit (cents)',
    )
    valid_until: str = Field(..., description='ISO 8601 timestamp when quote expires')


class RejectQuoteResponse(BaseModel):
    id: str = Field(..., description='Quote ID that was rejected')
    status: StripeQuoteStatus = Field(
        ..., description='New status (canceled after rejection)'
    )


class ResultSummary1(AffinityResult):
    result_type: ResultType


class ResultSummary2(ThermostabilityResult):
    result_type: ResultType1


class ResultSummary(RootModel[ResultSummary1 | ResultSummary2]):
    root: ResultSummary1 | ResultSummary2 = Field(
        ...,
        description='Discriminated union for result summaries.\n\nEnables type-safe handling of different assay result types (affinity vs\nthermostability) without forcing incompatible data into a single structure.\nThe `result_type` tag in serialized JSON identifies the variant.',
    )


class SequenceAddRequest(BaseModel):
    experiment_code: str = Field(
        ...,
        description='Human-readable experiment code (e.g., "PROJ-001")',
        examples=['PROJ-001'],
    )
    sequences: list[SequenceEntry] = Field(
        ..., description='Sequences to append to the experiment'
    )


class SequenceMetadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    vh: str | None = Field(
        None,
        alias='VH',
        description='Variable heavy chain sequence (required for ScFv).',
        examples=['EVQLVESGGGLVQPGGSLRLSCAASGFTFS'],
    )
    vl: str | None = Field(
        None,
        alias='VL',
        description='Variable light chain sequence (required for ScFv).',
        examples=['DIQMTQSPSSLSASVGDRVTITC'],
    )
    chain_order: list[str] | None = Field(
        None, description='Chain ordering for complex multi-chain formats.'
    )
    framework_regions: FrameworkRegions | None = None
    linker: str | None = Field(
        None,
        description='Flexible peptide linker connecting VH and VL domains.\n\nIf omitted for ScFv, defaults to `GGGGSGGGGSGGGGS` (Gly₄Ser)₃.',
        examples=['GGGGSGGGGSGGGGS'],
    )
    tag_location: TagLocation | None = None
    type: SequenceType | None = None


class TargetInfo(BaseModel):
    catalog_number: str = Field(..., description="Vendor's catalog/SKU number")
    details: TargetDetails | None = None
    id: str = Field(
        ..., description='Unique identifier for the target from the catalog'
    )
    name: str = Field(..., description='Product name of the target antigen')
    pricing: TargetPricing | None = None
    uniprot_id: str | None = Field(
        None,
        description='UniProt accession for the primary protein component.\nPresent on ~82% of targets; viral/non-standard proteins lack this\n(they have `details.ncbi_id` instead).',
        examples=['Q15116'],
    )
    url: str = Field(
        ...,
        description='URL to view this target in the catalog web UI',
        examples=[
            'https://targets.adaptyvbio.com/protein/f3b2afd0-f70b-5191-a90a-ae1e0545c744'
        ],
    )
    vendor_name: str = Field(
        ..., description='Vendor/supplier name (e.g., "ACRO Biosystems")'
    )


class CostEstimateResponse(BaseModel):
    breakdown: CostBreakdown | None = None
    incomplete: IncompleteCostEstimate | None = None
    warnings: list[str] | None = Field(
        None,
        description='Warnings about the estimate (e.g., unknown target, pricing limitations)',
    )


class ResultInfo(BaseModel):
    created_at: str = Field(..., description='ISO 8601 timestamp of result generation')
    data_package_url: str | None = Field(
        None, description='Data package URL, same as in the Foundry portal'
    )
    experiment_id: str = Field(..., description='Associated experiment identifier')
    id: str = Field(..., description='Unique identifier for the result')
    metadata: Any = Field(
        ..., description='Extended metadata beyond the summary (e.g. instrument info).'
    )
    result_type: str = Field(
        ..., description='Type of analysis result (e.g., "affinity", "thermostability")'
    )
    summary: list[ResultSummary] = Field(
        ...,
        description='Summary of key results (discriminated union by result_type tag)',
    )
    title: str = Field(..., description='Human-readable result title')


class SequenceInput(BaseModel):
    aa_string: AAString = Field(
        ...,
        description='Protein/peptide sequence in standard single-letter amino acid format.\n\nValid characters: A,C,D,E,F,G,H,I,K,L,M,N,P,Q,R,S,T,V,W,Y and colon for multichain.',
    )
    control: bool | None = Field(
        None, description='Whether the sequence should be treated as a control well'
    )
    metadata: SequenceMetadata | None = None


class SequenceValue(RootModel[AAString | SequenceInput]):
    root: AAString | SequenceInput = Field(
        ...,
        description='Flexible sequence input for experiment creation.\n\nAccepts a simple amino acid string or a rich object with control flag and metadata.',
    )


class ExperimentSpec(BaseModel):
    antigen_concentrations: list[float] | None = Field(
        None,
        description='Antigen concentrations to test (in nanoMolar)',
        examples=[[1000.0, 316.2, 100.0, 31.6, 0.0]],
    )
    experiment_type: ExperimentType = Field(
        ...,
        description='Assay type: `affinity`, `screening`, `thermostability`, `fluorescence`, `expression`, `epitope_binning`, or `enzyme_activity`',
    )
    method: Method | None = None
    n_replicates: int | None = Field(
        None,
        description='Number of technical replicates (minimum 1, recommended 3+)',
        examples=[3],
        ge=0,
    )
    parameters: Any | None = Field(
        None,
        description='Experiment-specific configuration beyond the common fields.\n\nUsed for internal pipeline routing; most experiments leave this null.\nWhen provided, stored as-is and returned in experiment detail.',
    )
    sequences: dict[str, SequenceValue] | None = Field(
        None,
        description='Sequences keyed by a human readable name. Accepts either simple amino acid strings\nor rich objects with control flags and metadata.',
    )
    target_id: str | None = Field(
        None,
        description='UUID of the target antigen from the catalog, as supplied on create.',
        examples=['c383cc1d-fe22-5dbf-953c-378bc073019d'],
    )


class CostEstimateRequest(BaseModel):
    experiment_spec: ExperimentSpec = Field(
        ...,
        description='Experiment specification for cost calculation (see ExperimentSpec for field details)',
    )


class CreateExpRequest(BaseModel):
    auto_accept_quote: bool = Field(
        False,
        description='Auto-accept the quote and create an invoice (without sending).\n\nWhen `true`, the system will:\n1. Create a Stripe quote (requires target_id and full pricing available)\n2. Finalize and accept the quote\n3. Create a draft invoice (not sent to customer)\n4. Advance the experiment to "Waiting for materials" status\n\nThis enables fully automated experiment submission pipelines where payment\nis handled externally or the organization has pre-approved billing.\nImplies `skip_draft: true`.',
    )
    experiment_spec: ExperimentSpec = Field(
        ...,
        description='Structured experiment definition (type, target, sequences, parameters)',
    )
    name: str = Field(
        ...,
        description='Human-readable name for the experiment',
        examples=['PD-L1 affinity panel'],
    )
    skip_draft: bool | None = Field(
        None,
        description='Bypass Draft status and submit directly for processing.\n\nWhen `true`, the experiment is created in "Waiting for confirmation"\nstatus instead of Draft, skipping the manual review step. Use this for\nautomated pipelines with pre-validated payloads.\n\nWhen an experiment is submitted with `skip_draft: true` and the target\nhas existing inventory materials, those materials are automatically\nlinked to expedite processing.',
    )
    webhook_url: str | None = Field(
        None,
        description='URL to which experiment status updates will be POSTed',
        examples=['https://example.com/webhook'],
    )


class ExpInfo(BaseModel):
    code: str = Field(
        ...,
        description='Unique experiment code (e.g., "EXP-2024-001") or request ID if not fulfilled',
    )
    costs: ExperimentCosts | None = None
    created_at: str = Field(
        ..., description='ISO 8601 timestamp of experiment creation'
    )
    experiment_spec: ExperimentSpec = Field(
        ...,
        description='Unified experiment specification (type, target, sequences, params)',
    )
    experiment_url: str = Field(
        ..., description='URL to view the experiment in the Foundry portal'
    )
    id: str = Field(..., description='Unique identifier for the experiment')
    name: str | None = Field(
        None,
        description='Human-readable name for the experiment (nullable in database)',
    )
    results_status: ResultsStatus = Field(
        ..., description='Indicates whether results are available for this experiment'
    )
    status: ExperimentStatus = Field(
        ..., description='Current lifecycle status of the experiment'
    )
    stripe_invoice_url: str | None = Field(None, description='URL to view/pay invoice')
    stripe_quote_id: str | None = Field(
        None,
        description='Stripe quote identifier (e.g. `qt_1Abc2Def`), when a quote exists.\n\nExposed so partner integrations and scenario runners can call the\n`/quotes/{quote_id}` family of endpoints without having to parse the\nID out of [`Self::stripe_quote_url`]. Value tracks the upstream Stripe\nquote; changes if the quote is regenerated (rare).',
    )
    stripe_quote_url: str | None = Field(
        None, description='URL to view quote in payment provider dashboard'
    )
