# generated by datamodel-codegen:
#   filename:  https://foundry-api-public.adaptyvbio.com/openapi.json
#   timestamp: 2026-01-06T16:21:59+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field, RootModel


class CreateExpResponse(BaseModel):
    experiment_id: str = Field(..., description="Unique identifier assigned to the new experiment")


class ExperimentConfirmationResponse(BaseModel):
    confirmed_at: str = Field(..., description="Timestamp when confirmation completed")
    experiment_id: str = Field(..., description="Experiment identifier")
    status: str = Field(
        ...,
        description='Experiment status after confirmation (e.g., "waiting_for_materials")',
    )
    stripe_invoice_id: str | None = Field(
        None, description="Stripe invoice identifier created during confirmation"
    )
    stripe_invoice_url: str | None = Field(
        None, description="Hosted invoice URL from Stripe (if available)"
    )


class ExperimentInvoiceResponse(BaseModel):
    experiment_id: str = Field(..., description="Experiment identifier")
    invoice_id: str | None = Field(None, description="Invoice ID when available")
    invoice_url: str | None = Field(None, description="Hosted invoice URL when available")
    status: str | None = Field(
        None, description="Invoice status (draft, open, paid, uncollectible, void)"
    )


class ExperimentQuoteResponse(BaseModel):
    amount_subtotal: int = Field(..., description="Subtotal amount (in the smallest currency unit)")
    amount_total: int = Field(..., description="Total amount (in the smallest currency unit)")
    currency: str = Field(..., description='ISO currency code (e.g., "usd")')
    experiment_id: str = Field(..., description="Experiment identifier")
    expires_at: str | None = Field(
        None,
        description="RFC3339 timestamp for when the quote expires (if provided by Stripe)",
    )
    quote_id: str = Field(..., description="Stripe quote identifier")
    status: str = Field(..., description="Stripe quote status")
    updated_at: str | None = Field(None, description="RFC3339 timestamp for the last update time")


class ExperimentStatus(str, Enum):
    draft = "draft"
    waiting_for_confirmation = "waiting_for_confirmation"
    canceled = "canceled"
    waiting_for_materials = "waiting_for_materials"
    in_production = "in_production"
    quote_sent = "quote_sent"
    in_queue = "in_queue"
    data_analysis = "data_analysis"
    in_review = "in_review"
    done = "done"


class ExperimentType(str, Enum):
    affinity = "affinity"
    screening = "screening"
    thermostability = "thermostability"


class FrameworkRegions(BaseModel):
    ch: str | None = Field(None, description="Constant heavy chain region")
    cl: str | None = Field(None, description="Constant light chain region")


class Method(str, Enum):
    bli = "bli"
    spr = "spr"


class ResultsStatus(str, Enum):
    none = "none"
    partial = "partial"
    all = "all"


class SequenceType(str, Enum):
    sc_fv = "sc_fv"
    fab = "fab"
    single_chain = "single_chain"
    ig_g = "ig_g"


class TagLocation(str, Enum):
    n = "N"
    c = "C"


class TargetInfo(BaseModel):
    catalog_number: str = Field(..., description="Vendor's catalog/SKU number")
    id: str = Field(..., description="Unique identifier for the target from the catalog")
    name: str = Field(..., description="Product name of the target antigen")
    vendor_name: str = Field(..., description='Vendor/supplier name (e.g., "ACRO Biosystems")')


class TargetListItem(BaseModel):
    catalog_number: str = Field(..., description="Vendor's catalog/SKU number")
    id: str = Field(..., description="Unique identifier for the target from the catalog")
    name: str = Field(..., description="Product name of the target antigen")
    vendor_name: str = Field(..., description='Vendor/supplier name (e.g., "ACRO Biosystems")')


class UpdateListItem(BaseModel):
    experiment_code: str = Field(..., description="Experiment code for grouping and display")
    experiment_id: str = Field(..., description="ID of the experiment that generated this update")
    id: str = Field(..., description="Unique identifier for this update event (ULID)")
    name: str = Field(..., description="Public-facing name/title of the update")
    timestamp: str = Field(..., description="ISO 8601 timestamp when the update occurred")


class ExpListItem(BaseModel):
    code: str = Field(..., description='Unique experiment code (e.g., "EXP-2024-001")')
    created_at: str = Field(..., description="ISO 8601 timestamp of experiment creation")
    experiment_type: ExperimentType = Field(
        ..., description="Experiment discriminator from the spec"
    )
    experiment_url: str = Field(..., description="URL to view the experiment in the Foundry portal")
    id: str = Field(..., description="Unique identifier for the experiment")
    name: str = Field(..., description="Human-readable name for the experiment")
    results_status: ResultsStatus = Field(
        ..., description="Indicates whether results are available for this experiment"
    )
    status: ExperimentStatus = Field(..., description="Current lifecycle status of the experiment")
    stripe_invoice_id: str | None = Field(None, description="Stripe invoice ID if invoiced")
    stripe_quote_id: str | None = Field(None, description="Stripe quote ID if quote was generated")


class SequenceMetadata(BaseModel):
    chain_order: list[str] | None = Field(None, description="Chain ordering for complex formats")
    framework_regions: FrameworkRegions | None = None
    linker: str | None = Field(None, description="Linker sequence (for ScFv)")
    tag_location: TagLocation | None = None
    type: SequenceType | None = None
    vh: str | None = Field(None, description="Heavy chain variable region (for ScFv)")
    vl: str | None = Field(None, description="Light chain variable region (for ScFv)")


class TargetList(BaseModel):
    page: int = Field(..., description="Current page number (1-indexed)", ge=0)
    per_page: int = Field(..., description="Number of items per page", ge=0)
    targets: list[TargetListItem] = Field(
        ..., description="Array of target summary items for the current page"
    )
    total: int = Field(..., description="Total number of targets available across all pages", ge=0)


class UpdateList(BaseModel):
    next_cursor: str | None = Field(
        None,
        description="Cursor for next page (use the last update's ID as cursor)\nNone if this is the last page",
    )
    updates: list[UpdateListItem] = Field(..., description="Array of recent update events")


class ExpList(BaseModel):
    experiments: list[ExpListItem] = Field(..., description="Array of experiment summaries")


class SequenceInput(BaseModel):
    control: bool | None = Field(
        None, description="Whether the sequence should be treated as a positive control"
    )
    fasta: str = Field(
        ...,
        description="Protein/peptide sequence in standard single-letter amino acid format",
    )
    metadata: SequenceMetadata | None = None


class SequenceValue(RootModel[str | SequenceInput]):
    root: str | SequenceInput = Field(
        ...,
        description="Flexible sequence input for experiment creation.\n\nAccepts a simple FASTA string or a rich object with control flag and metadata.",
    )


class ExperimentSpec(BaseModel):
    antigen_concentrations: list[float] | None = Field(
        None, description="Antigen concentrations to test (in Molar)"
    )
    experiment_type: ExperimentType = Field(
        ..., description="Assay type: `affinity`, `screening`, or `thermostability`"
    )
    method: Method | None = Field(
        None, description="Measurement method (BLI or SPR). Defaults to BLI."
    )
    n_replicates: int | None = Field(
        None,
        description="Number of technical replicates (minimum 1, recommended 3+)",
        ge=0,
    )
    parameters: Any | None = Field(None, description="Additional experiment-specific parameters")
    sequences: dict[str, SequenceValue] | None = Field(
        None,
        description="Sequences keyed by a human readable name. Accepts either simple FASTA strings\nor rich objects with control flags and metadata.",
    )
    target_id: str | None = Field(None, description="UUID of the target antigen from the catalog")


class CreateExpRequest(BaseModel):
    experiment_spec: ExperimentSpec = Field(
        ...,
        description="Structured experiment definition (type, target, sequences, parameters)",
    )
    id: str | None = Field(
        None,
        description="Experiment UUID for updates. Omit to create a new experiment.",
    )
    name: str = Field(..., description="Human-readable name for the experiment")
    webhook_url: str | None = Field(
        None, description="URL to which experiment status updates will be POSTed"
    )


class ExpInfo(BaseModel):
    code: str = Field(
        ...,
        description='Unique experiment code (e.g., "EXP-2024-001") or request ID if not fulfilled',
    )
    created_at: str = Field(..., description="ISO 8601 timestamp of experiment creation")
    experiment_spec: ExperimentSpec = Field(
        ...,
        description="Unified experiment specification (type, target, sequences, params)",
    )
    experiment_url: str = Field(..., description="URL to view the experiment in the Foundry portal")
    id: str = Field(..., description="Unique identifier for the experiment")
    name: str = Field(..., description="Human-readable name for the experiment")
    results_status: ResultsStatus = Field(
        ..., description="Indicates whether results are available for this experiment"
    )
    status: ExperimentStatus = Field(..., description="Current lifecycle status of the experiment")
    stripe_invoice_id: str | None = Field(None, description="Stripe invoice ID if invoiced")
    stripe_quote_id: str | None = Field(None, description="Stripe quote ID if quote was generated")
